### ISSUE TITLE
Unable to cast object of type 'System.Windows.Media.LineSegment' to type 'System.Windows.Media.PolyLineSegment'

### ISSUE THREAD

**Issue by znakeeye** [XpsToPdf/XpsToPdf#11]
See attached sample project. When writing path geometry `M 2.779 0.937 L 0.85 2.92 Q 0.774 3.046 0.705 3.176 Z` an exception is thrown.
```
System.InvalidCastException: Unable to cast object of type 'System.Windows.Media.LineSegment' to type 'System.Windows.Media.PolyLineSegment'.
   at PdfSharp.Xps.Rendering.WpfUtils.FlattenSegment(Point startPoint, PolyQuadraticBezierSegment seg)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteSegment(PolyQuadraticBezierSegment seg)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteGeometry(PathGeometry geo)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WritePath(Path path)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElement(XpsElement element)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElements(XpsElementCollection elements)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteCanvas(Canvas canvas)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElement(XpsElement element)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElements(XpsElementCollection elements)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteCanvas(Canvas canvas)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElement(XpsElement element)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElements(XpsElementCollection elements)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteCanvas(Canvas canvas)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElement(XpsElement element)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElements(XpsElementCollection elements)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteCanvas(Canvas canvas)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElement(XpsElement element)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElements(XpsElementCollection elements)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteCanvas(Canvas canvas)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElement(XpsElement element)
   at PdfSharp.Xps.Rendering.PdfContentWriter.WriteElements(XpsElementCollection elements)
   at PdfSharp.Xps.Rendering.PdfRenderer.RenderPage(PdfPage page, FixedPage fixedPage)
   at PdfSharp.Xps.XpsConverter.Convert(XpsDocument xpsDocument, String pdfFilename, Int32 docIndex)
```

[PdfCrashTest.zip](https://github.com/XpsToPdf/XpsToPdf/files/14720988/PdfCrashTest.zip)

**Comment by Orace** [comment]
Available here: https://www.nuget.org/packages/XpsToPdf/1.0.6
